### ISSUE TITLE
MARKBOT ISSUES

### ISSUE THREAD

**Issue by Jessica-Lee123** [Jessica-Lee123/masthead-semantics#1]
I swear, it's out to get me!!!!! @hellachella

**Comment by Jessica-Lee123** [comment]
<img width="1870" alt="Stuck here" src="https://user-images.githubusercontent.com/77642609/107830902-c7b5d980-6d5a-11eb-93d4-06d0029d4ca2.png">

**Comment by Jessica-Lee123** [comment]
Also sending this here
![Uploading Screen Shot 2021-02-12 at 3.07.28 PM.png…]()

**Comment by hellachella** [comment]
Yup Yup. You cant put any of the content code into the head of a document. The head of the document is not for anything that shows visually on the website. It's secret hidden stuff for the browser to interpret. All of the content goes between the body tags. 

```
<!DOCTYPE html>
<html lang="en-ca">
<head>
  <meta charset="utf-8">
  <title>The Solar System</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>

<body>

 ALL h1, header, img, links, text. ALL content goes between the body tags. 
 Anything in the head of the document cannot be seen on a browser. It's for metadata 

</body>
</html>
```

**Comment by Jessica-Lee123** [comment]
<img width="2560" alt="Screen Shot 2021-02-18 at 12 53 04 PM 1" src="https://user-images.githubusercontent.com/77642609/108399611-493cba00-71e8-11eb-879a-f1ec6a671cf4.png">

@hellachella 

I tried to make the changes you suggested, but I must not have implemented them properly, as even more errors came up in Markbot.

**Comment by hellachella** [comment]
This isn't looking bad at all. You need to wrap your header content into a `header` tag and use menu>edit>lines>autoindent after selecting everything. 

```
<header>
  <h1>The Solar System</h1>
  <img src="images/logo.svg" alt="">
  <nav>
    <ol>
      <li><a href="#">Stars</a></li>
      <li><a href="#">Terrestrial planets</a></li>
      <li><a href="#">Gas giants</a></li>
      <li><a href="#">Dwarf planets</a></li>
      <li><a href="#">Asteroids</a></li>
      <li><a href="#">Comets</a></li>
    </ol>
  </nav>
</header>
```
